### ISSUE TITLE
[Bug] "Pause/Unpause suspension of this tab" doesn't work

### ISSUE THREAD

**Issue by frykauf** [gioxx/MarvellousSuspender#119]

**Comment by denismattos** [comment]
I'm experiencing the same issue.  
The "Not now" button simply doesn't respond for most pages.  
It'll still work normally for a few (couldn't notice a pattern of webpages for which it'll work) and, in yet rarer cases, it'll appear to not work (i.e. the ribbon on top of the extension's menu will stay the same), but the command **will** work and the suspension will be paused. Yesterday, one of these later, rarer cases happened and I intended to test whether clicking the "Not now" button again would reverse the pause, but I forgot to do it right away and ended up losing the tab due to an unrelated Chrome crash.

**Comment by baz357** [comment]
See https://github.com/gioxx/MarvellousSuspender/issues/86

**Comment by gioxx** [comment]
Duplicated, see #86
