### ISSUE TITLE
Tab will suspend automatically (not now) - "not now" not working

### ISSUE THREAD

**Issue by xodotLBO** [gioxx/MarvellousSuspender#124]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6.2
 * Browser name & version: Chrome 91.0.4472.77
 * Operating system & version: Win10x64 20h2 

"Not now" for temporarily pausing the suspension/adding whitelist for a website doesn't work.

**Comment by sherkot** [comment]
Hi xodotLBO,
as you can see in the #86 topic, we have fixed this issue. If you want to share more information, feel free to comment in that dicussion

**Comment by xodotLBO** [comment]
Hasn't been fixed (chrome web store) but my bad for not looking for existing issue.

**Comment by Thiefsie** [comment]
I'm not seeing this fixed with the github build or other. Chrome build is same version as Github build too? Manually installed github with no result. 

"Not now" button does nothing.

Extension version: 7.1.6.2 Github
Browser name & version: Version 93.0.4577.82 (Official Build) (64-bit)
Operating system & version: Win10x64 20h2
