### ISSUE TITLE
June 14 update 91.0.4472.106 [Fixed?] Blank/White screen problem workaround (Chrome 91 update)

### ISSUE THREAD

**Issue by PatrickL546** [gioxx/MarvellousSuspender#125]
### As of update  91.0.4472.106, I've not seen the blank screen happening. Chrome just loads it normally like before. Can anyone else check?

The Extention is very buggy after the Chrome 91 update and I would just like to share a workaround I found for this particular problem. Note that this fix doesn't stay forever.

If you see this, this might help

![image](https://user-images.githubusercontent.com/75874561/120907960-105c1000-c634-11eb-9d57-105bcfcce01b.png)

1. Go to settings

![image](https://user-images.githubusercontent.com/75874561/120908004-66c94e80-c634-11eb-8538-a20a1f75f47f.png)

2. Toggle "Apply Chrome's built-in memory-saving when suspending" on/off and wait for the tabs to come back to normal.

![image](https://user-images.githubusercontent.com/75874561/120887198-7d818e00-c5bf-11eb-8a27-229c5c4e5ea1.png)

If it doesn't automatically come back to normal, just close the window and Ctrl+Shift+T to restore the whole window. Or hold Ctrl+Tab to go through all your tabs and reload it.

I've been using this trick since the update and I hope this helps you until a fix is found.

**Comment by baz357** [comment]
Thanks for sharing! I didn't see this particular issue myself but will use this if it shows up here.

**Comment by bobsage123** [comment]
This doesn't seem to be working for me. I don't know if it's because I have 100+ tabs suspended.

**Comment by q00u** [comment]
This does not work for me either. It brought back _some_ of the tabs (or at least the favicons) but not all of them.

And when I click on some of these recovered tabs, they revert to white screens.

And toggling this setting a second time doesn't appear to do anything.

This is on Chrome 91.0.4472.101

**Comment by PatrickL546** [comment]
This seems to only work on low tab amounts. I usually have 20 tabs and it works. Sometimes it takes some time but I keep the options tab opened and go through each page to reload them.

**Comment by x94fujo6rpg** [comment]
I think I have found one of the reasons cause this:

I migrated from tgs to this version

When I load the `session.txt`
Although MarvellousSuspender will convert it to its own version
but the `window.history` will contain `chrome-extension://old_extension_id/suspended.html#ttl=...`  
and it will be blocked by chrome during restart
cause blank tab

---
example
when I load from my `session.txt`
MarvellousSuspender will load `chrome-extension://old_extension_id/suspended.html#ttl=...`  
and convert to `chrome-extension://MarvellousSuspender_extension_id/suspended.html#ttl=...`  

during restart chrome
because of the tab have `window.history` `chrome-extension://old_extension_id/suspended.html#ttl=...`
chrome will detect the ID is bad extension and block it
after the block
even MarvellousSuspender convert it
the tab will stay blank

use `window.history.back()` will go back to `chrome-extension://old_extension_id/suspended.html#ttl=...`
it will show the chrome error page `ERR_BLOCKED_BY_CLIENT`
use `window.history.forward()` go to `chrome-extension://MarvellousSuspender_extension_id/suspended.html#ttl=...`
the tab will be fix
but blank tab will happen again after restart chrome
because chrome save the `window.history`...

---
I fix my tabs by replace all old extension ID in the `session.txt` with MarvellousSuspender extension ID (using file editor)
and use this new file
all tabs loaded properly
even after restart chrome

---
Suggestions
Replace all old ID with MarvellousSuspender's own ID immediately after read the session file
Avoid the need of url converting during restart chrome

**Comment by PatrickL546** [comment]
This seems to be fixed on chrome 91.0.4472.106.
https://bugs.chromium.org/p/chromium/issues/detail?id=1216788
