### ISSUE TITLE
Suspended tabs name with 3 dots and white page in Private Session

### ISSUE THREAD

**Issue by gioxx** [gioxx/MarvellousSuspender#166]
@CollinChaffin I gotta tell you - as a long-time user of TGS and now TMS, I would _love_ to see the session management stuff ripped out. As you point out, there are far more powerful session management extensions out there, and it would significantly reduce the code overhead for @gioxx and crew to not have to maintain it. 
 
With regard to the original issue, I did want to add one additional fix since I've been having the same issue on incognito tabs:

In addition to the above code changes in `js/gsUtils.js` I modified the `isFileTab` method in the same way, as follows:

```js
isFileTab: function(tab) {
  if (!tab || typeof tab == "undefined") {
    return false;
  }
  const url = tab.url || tab.pendingUrl;
```

After making this additional change I have had no other issues. 

**Ninja edit:** I forgot to thank everyone for the kind shout-outs. I'm glad I was able to help other people resolve their issue, and especially to help @gioxx and team.

_Originally posted by @rex in https://github.com/gioxx/MarvellousSuspender/issues/161#issuecomment-1068794437_

**Comment by rex** [comment]
Hey @gioxx I actually identified _another_ small change. It appears despite my best efforts to ensure a valid tab state with the `if (!tab...` sanity check, the `url` ends up being invalid anyway. This is really, _really_ annoying behavior by Chrome.

At this point, would it be easier/more helpful to you if I opened a pull request to collect my proposed changes into one place? I think I'll go ahead and do that to make it easier to discuss, anyway.

**Comment by gioxx** [comment]
Sure @rex, can certainly be convenient.

**Comment by rex** [comment]
Sweet, I'll do that @gioxx :) And I'll include in the description a brief explanation of why the additional change is necessary. Honestly, this is a really irritating issue on Chrome's part but these small changes should resolve most or all of this.

Super super short version, it seems like Chrome is now triggering these tab state changes _far_ more often and for a greater variety of states than whatever the extension was designed for. The code was written in a way that it could confidently assume certain properties were available, but now Chrome is executing this code at times where those properties _aren't_ available. 

Hopefully that made things clearer instead of more confusing.

**Comment by rex** [comment]
PR #167 opened and ready for your review @gioxx :) With explanation included in the description, with screenshots.
