### ISSUE TITLE
Favicon and title missing from suspended tabs after starting computer

### ISSUE THREAD

**Issue by brank87** [gioxx/MarvellousSuspender#189]
* Extension version: v7.1.6.2
 * Browser name & version: Chrome 104.0.5112.79
 * Operating system & version: MacOS Monterrey 12.0
 
![2022-08-09_09-35-14](https://user-images.githubusercontent.com/6234182/183591804-b83f554f-50b4-49c9-9f8c-755f928e6622.png)

Screencast reproducing: [https://i.imgur.com/jiHAs98.mp4](https://i.imgur.com/jiHAs98.mp4)

**Comment by Technetium1** [comment]
Duplicate of https://github.com/gioxx/MarvellousSuspender/issues/188 and https://github.com/gioxx/MarvellousSuspender/issues/185 which has a temporary fix

Here's a direct link to the fix for macOS, followed by an AppleScript solution as well https://github.com/gioxx/MarvellousSuspender/issues/185#issuecomment-1209251333

**Comment by mendelsphotography** [comment]
@brank87 Might as well close this as this is already discussed elsewhere as mentioned above.

**Comment by brank87** [comment]
Sorry guys. Thanks. Closing now.
