### ISSUE TITLE
Marvellous Suspender vs Chrome Memory Saver

### ISSUE THREAD

**Issue by Crypto-Spartan** [gioxx/MarvellousSuspender#218]
Hi, I'm looking for information regarding differences between Marvellous Suspender and Chrome's Memory Saver. A couple of questions I had:

- what are the pros/cons of using one over the other? is one objectively better? or is it a scenario case where one might save more memory, but the other provides a snappier experience?
- what problems (if any) exist if you have Chrome Memory Saver enabled while also using Marvellous Suspender?

I tried to do some research on this, but I wasn't able to find many discussions around it. I came across this reddit post, but it seems that no one there knew the answer either: https://reddit.com/r/chrome/comments/11uesf8/chrome_memory_saver_vs_the_marvellous_suspender/

I would be very grateful for any information regarding this, even if it's not a lot

**Comment by Technetium1** [comment]
No issues using both at once. Memory saver in Chrome isn't on a 'timer of inactivity', so it unloads when it feels like it. If you do really, really large sessions, then the memory saver is inferior in comparison.

**Comment by Crypto-Spartan** [comment]
Can you provide any additional details as to how the two functions work and how they interact with one another? I haven't been able to find a lot of documentation in my searches.

**Comment by Technetium1** [comment]
I'm telling just based off of my experiences. You won't find any documentation on this… You'll have to actually read some of the code that does the suspension in Chrome's memory saver to know how theirs works.

I don't like that memory saver when used alone will reload the tab when you go to it. Sometimes I tab through 20 suspended tabs in a window to find a specific thing, and I don't want to reload all 20 pages. That's definitely a big difference, because here a custom suspend page is rendered, which only _optionally_ reloads on focus.

Maybe you want to start at this: https://github.com/gioxx/MarvellousSuspender/blob/master/src/js/gsTabSuspendManager.js

Google is in charge of doing heuristics to determine what to suspend, no such thing here, only a timer.
https://github.com/chromium/chromium/commit/fbb6598dc720a79b68452316fed98b6461b0da97
https://github.com/chromium/chromium/commit/dc5326878563997d23a92671f6d78c9f79f202f7

**Comment by eNdEmiOn** [comment]
Yeah I wouldn't mind some more info as well. I mean why for instance am I observing my tabs graying out twice as in two steps of opaqueness? Suspend, hibernate what are the differences?

One important difference I can tell you about though is that chromes memory saver won't help speed up the startup process of your browser as it will not remember which tabs were suspended so it will reload everything.

**Comment by Crypto-Spartan** [comment]
Anyone coming to this thread looking for info, check out #197, specifically [here](https://github.com/gioxx/MarvellousSuspender/issues/197#issuecomment-1725443677) & [here](https://github.com/gioxx/MarvellousSuspender/issues/197#issuecomment-1728721401).
