### ISSUE TITLE
Version 7.1.6.2 released in chrome store but not github

### ISSUE THREAD

**Issue by Github852** [gioxx/MarvellousSuspender#79]
What is new in the new version? Why hasn't it been released in GitHub yet? I hope this doesn't turn out like The Great Suspender.

Edit: Read below for more information, it's been resolved.

**Comment by Github852** [comment]
A suggestion make updates optional

**Comment by mrjohncarter** [comment]
I also received the notification to Update... A bit worried right now... Hope so someone would clarify.... what's goin on....

**Comment by hovenko** [comment]
Maybe related to this comment:
https://github.com/greatsuspender/thegreatsuspender/issues/1175#issuecomment-793665826

But the version number 7.1.6.2 should also be a git commit tag on this repo.

**Comment by NANI-SORE** [comment]
I did a quick compare of current github and store versions, the only differences I found are some localization files changes and manifest being reordered.
The dev probably just forgot to put a commit tag.

**Comment by Destroy666x** [comment]
Quite a bad thing to forget considering it's a fork of a malicious extension...

**Comment by kuso-ge** [comment]
an update log would also be appreciated

**Comment by gioxx** [comment]
Sorry for the delay guys.
The last time I had uploaded a new version of the extension to the Chrome store, it took Google over a week to release it. This time it took much less time and the extension was released before I released the new package on GitHub.

https://github.com/gioxx/MarvellousSuspender/releases/tag/7.1.6.2

7.1.6.2 is the new version of Marvellous Suspender. This new version integrates all the improvements of the issues that you have opened and that we have closed with @sherkot in the meantime, including new features, corrections and improvements.

As already said several times, I understand the lack of confidence because of what happened with The Great Suspender, but I reiterate the concept: I'm not here to put malware in the extension, I'm a Mozilla man and more generally of the Open Source for more than 20 years and I have no intention to sell the extension to some unknown as happened with the original.

This is a "Happy Easter present" for you, after a long period of absence (I've become a dad in the meantime), also due to the Covid-19 disease I'm still getting over (yes, I'm still in quarantine inside the walls of my house).

**Comment by Github852** [comment]
Congratulations on becoming a dad! I hope you recover soon from Covid, and thank you very much for clarifying.

**Comment by mrjohncarter** [comment]
> Sorry for the delay guys.
> The last time I had uploaded a new version of the extension to the Chrome store, it took Google over a week to release it. This time it took much less time and the extension was released before I released the new package on GitHub.
> 
> https://github.com/gioxx/MarvellousSuspender/releases/tag/7.1.6.2
> 
> 7.1.6.2 is the new version of Marvellous Suspender. This new version integrates all the improvements of the issues that you have opened and that we have closed with @sherkot in the meantime, including new features, corrections and improvements.
> 
> As already said several times, I understand the lack of confidence because of what happened with The Great Suspender, but I reiterate the concept: I'm not here to put malware in the extension, I'm a Mozilla man and more generally of the Open Source for more than 20 years and I have no intention to sell the extension to some unknown as happened with the original.
> 
> This is a "Happy Easter present" for you, after a long period of absence (I've become a dad in the meantime), also due to the Covid-19 disease I'm still getting over (yes, I'm still in quarantine inside the walls of my house).

@gioxx Thank You very much for the quick response, And Congratulations on Being Father.... Also, I just pray that you Get Well Soon.

I am glad we have people like you in our community.

**Comment by pantantrollo** [comment]
> This is a "Happy Easter present" for you, after a long period of absence (I've become a dad in the meantime), also due to the Covid-19 disease I'm still getting over (yes, I'm still in quarantine inside the walls of my house).

Hi,
Above all, recovering from your health comes first. Congratulations on being a parent :-)

**Comment by Evie-irl** [comment]
> A suggestion make updates optional

An option to not get the annoying "pls update haha" popup every so often would be great.

**Comment by macsunmood** [comment]
> > A suggestion make updates optional
> 
> An option to not get the annoying "pls update haha" popup every so often would be great.

I second that. And what about updating while having 1000+ tabs open on different virtual desktops? Will the structure remain untouched ? Will all the suspended tabs close and load back ?

@gioxx congrats and recover soon! ;)

**Comment by gioxx** [comment]
> 
> 
> A suggestion make updates optional

interesting option. I don't know if it's feasible and I don't know how much difficulty it requires to do it (on Firefox you can make updating any extension optional, on Chrome you can't, so a change has to be made to the source code). I'll reserve the right to take a look at it and see if it's possible to proceed.



> 
> 
> > A suggestion make updates optional
> 
> An option to not get the annoying "pls update haha" popup every so often would be great.

That window is useful because, especially for those who have many tabs, it reminds the user to create a backup before updating and losing (in the worst case scenario) the tabs left open and suspended. Do you really think it is something superfluous and would avoid opening it by proceeding directly with the update? I am open to any suggestion.

**Comment by CameosVatican** [comment]
Hello Giovanni

Firstly, congratulations on becoming a Dad.  Sleep-haha-wtf-is-that... 🥴

Not sure if this is related to the 7.1.6.2 update, but none of my tabs would refresh, I went hunting in my extensions vault and I got a Chrome alert that the extension _**may have been corrupted**._  Nearly had kittens myself, at the thought of manually having to reload 937 tabs. 😳

I've clicked repair, and I _think_ I've rescued them.  Just posting this in case it alarms anyone else.

Thanks for all you do – foc – Giovanni.  It _is_ appreciated. Especially as you're still recovering from COVID-19.  Long COVID is an absolute bugger. 😒

<img width="1680" alt="Marvellous Suspender corrupted? Seems to have been auto-disabled  🤔" src="https://user-images.githubusercontent.com/70779377/113778037-cf26ad00-9723-11eb-8b43-6d757796f2e2.png">
<img width="402" alt="Now saying it's been corrupted? 🤔 Marvellous Suspender" src="https://user-images.githubusercontent.com/70779377/113778416-3d6b6f80-9724-11eb-91d7-556b446f7bf4.png">

**Comment by gioxx** [comment]
Ciao @CameosVatican, fortunately yours is the only report about the corrupted extension, also fortunately it was possible to repair it quickly. So thank you very much for your report and even more for your good luck, the hours of sleep certainly lack but although the road is difficult, it is absolutely beautiful to face together with the baby! 👊🍻

**Comment by sherkot** [comment]
We continue to discuss about that in  #84
