### ISSUE TITLE
This is not an issue, but a Thank You regard.

### ISSUE THREAD

**Issue by K0media** [gioxx/MarvellousSuspender#83]
Hi there. I heard about all the turmoil and takedown about a month or 2 ago (from the date I'm composing this) regarding TGS.

I was really, REALLY excited with the project and saw the translation (in my locale) was missing.

So I offered my help. The developer @deanoemcke gave me the instructions and I had to do all the process manually.

I asked gently to host the strings on Crowdin, but I had to do everything manually with Notepad++.

(I'd send the screenshot of the project here, but perhaps it's not saved in my computer anymore.)

Here's the issue I mentioned it:
https://github.com/greatsuspender/thegreatsuspender/issues/894

And after I got everything done and reviewed, after several months (_or even a year later_) it was finally pushed in live.
https://twitter.com/Komedia007/status/1266507808637321218

Well, my desire had been fulfilled, since I used to install on my customers' machines, right after a fresh install of Windows. (In free time I work repairing computers, so that is my extra job.)

When I didn't come to realize, this happened and now **I wanted just to thank you for maintaining this.** Everything happened just so quick, the news came in and I was lost not knowing what to do.

I **also want to thank you so much for hosting the strings on Crowdin** (something that didn't happen in the past). That eases stuff A LOT just in case for getting things pushed in live quickly.

**I want to keep offering my volunteer work as a translator for this project.** I'm very confident that it's going to grow even more after this takeover and forking the project.

[I read your blog article](https://gioxx.org/2021/02/06/the-marvellous-suspender-hello-world/#en-us) (I'm about to leave a comment there) and I just don't know how to thank you enough for all of this. The volunteer job is amazing, and I'm glad that you could make it out to get this kept on the road.

As in conclusion, **I'd just like to ask whether I could become a proofreader of the project for PT-BR localization**, just like I was doing before. I'll be happy to help whenever new things and ideas come out, so that's the least that can be done by me for now.

If there's no one else taking care of it, please accept my kind regards and best wishes for all of this.

(PS: Idk if this will make you cry or something, but that's not the goal. I just wanted to keep this growing stronger than ever. My volunteer services are just to make sure everything will be alright in the future for this.)

If anything comes up, **you can tip me here or some other places** like it's pointed in **my communication channels. (Telegram, WhatsApp, here, email, etc.)**
**Here's the link** in case you want to reach me out via other channels:
https://my.bio/K0media

That's all for now. **Thank YOU again. Stay strong.** 🦾🙏🏻

**Comment by gioxx** [comment]
Ciao @K0media! 😊
I can do nothing but thank you for your wonderful message and your great work in the past. I decided to help and take care of the old The Great Suspender (today The Marvellous Suspender) because, like many other users, I was orphaned of a very good extension.

As already said, I'm not a real developer (I'm a System Administrator) but I know how to understand and move in the code, Marco (@sherkot) is giving me a great help (and he is a developer for real) and without him all this would not have been possible.

I want to use this thank you to reiterate the key concept: The Marvellous Suspender is everyone's extension, anyone can collaborate and I pray to anyone who has the skills to give us a hand to solve problems, give support to users, improve the extension where possible.

What I can do is to continue to take care of this repository and upload new versions of the extension to the Chrome Store so that all users can enjoy the most up-to-date version of the extension, protecting the extension from malicious code and third parties who want to buy it to make it end up as bad as The Great Suspender.

If in the future I won't be able to take care of The Marvellous Suspender, it will be my care to find someone who will do it for me, who shares my same philosophy and who won't compromise the users' trust. All this always warning the community that lives around this project.

Thanks again for your support.
