### ISSUE TITLE
Bright flash when opening suspended tab in dark mode

### ISSUE THREAD

**Issue by iwaszko** [gioxx/MarvellousSuspender#90]
I'm using a dark mode on my system and consequently in Chrome and also have a Dark theme enabled in the MarvellousSuspender. However, when navigating to suspended tabs, there's a short flash of white content that I find quite unpleasant for my eyes in low-light conditions.

Here's a short example: 
![Screen Recording 2021-04-07 at 03 38 46](https://user-images.githubusercontent.com/1711875/113798514-97cff480-9753-11eb-8d11-9a4463fa0dee.gif)

 * Extension version: 7.1.6.1
 * Browser name & version: Chrome 89.0.4389.114 (Official Build) (x86_64)
 * Operating system & version: macOS Catalina 10.15.1

**Comment by 0x7145** [comment]
I'm experiencing something similar in light mode. My suspended tabs take up to 5 seconds to display the placeholder page and allow me to reload, which is really annoying.

I currently have 80 tabs open (with about 70 of them suspended), but I have previously used the extension with many more tabs open. This problem started to appear after the last update.

- Extension version: 7.1.6.2
- Browser name & version: Chrome 87.0.4280.88 (Build oficial) (x86_64)
- Operating system & version: OS X Yosemite 10.10.5

**Comment by sherkot** [comment]
Hi @iwaszko, we just tried to reproduce the issue.
We have come to the conclusion that, independently from the dark mode of TMS, the issue is related to the loading of JS in Chrome. We have tried to reproduce using other themes, colours, chromium-based alternative browsers, with same result in every scenario.
We now mark this issue as wontfix, really sorry about that. 
If anyone can solve this issue, please be welcome to cooperate and propose a pull request.
